# Dependencies
highlighter:      pygments

# Setup
title:            Ye Yuan
tagline:          'Postdoc'
description:      'I am a Postdoc at UC Berkeley.'
url:              http://yy311.github.io
baseurl:          /
cover_image: /public/zion.png

author:
name:           'Ye Yuan'
email:          ye.yuan@outlook.com

paginate:         5
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
 - name: Biography
    loc: /bio.html
  - name: Research
    loc: /research.html
  - name: Teaching
    loc: /teaching.html
  - name: Publication
    loc: /publication.html
 
